<?php

namespace App\Http\Controllers\Certificates;

use App\Http\Controllers\Controller;
use App\Models\CertificateEvent;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CertificateEventAwardController extends Controller
{
    public function index(Request $request, int $eventId): JsonResponse
    {
        $event = $this->getSchoolEventOrFail($request, $eventId);

        return response()->json([
            'data' => $this->awardOptionsFromMetadata($event),
        ]);
    }

    public function store(Request $request, int $eventId): JsonResponse
    {
        $event = $this->getSchoolEventOrFail($request, $eventId);

        $validated = $request->validate([
            'award_title' => 'required|string|max:255',
        ]);

        $newTitle = $this->normalizeAwardTitle($validated['award_title']);
        if ($newTitle === '') {
            return response()->json([
                'message' => 'Award title is required.',
                'errors' => ['award_title' => ['Award title is required.']],
            ], 422);
        }

        if ($this->isAutoGeneratedAwardTitle($newTitle)) {
            return response()->json([
                'message' => 'Participant/Participation/Attendee/Attendance are auto-generated from attendance setup and cannot be added manually.',
                'errors' => ['award_title' => ['This award type is auto-generated and cannot be added manually.']],
            ], 422);
        }

        $existing = $this->awardOptionsFromMetadata($event);
        $existing[] = $newTitle;

        $this->saveAwardOptions($event, $existing);

        return response()->json([
            'message' => 'Award option added.',
            'data' => $this->awardOptionsFromMetadata($event->fresh()),
        ], 201);
    }

    public function destroy(Request $request, int $eventId): JsonResponse
    {
        $event = $this->getSchoolEventOrFail($request, $eventId);

        $validated = $request->validate([
            'award_title' => 'required|string|max:255',
        ]);

        $target = strtolower($this->normalizeAwardTitle($validated['award_title']));
        $remaining = collect($this->awardOptionsFromMetadata($event))
            ->reject(fn (string $item) => strtolower($item) === $target)
            ->values()
            ->all();

        $this->saveAwardOptions($event, $remaining);

        return response()->json([
            'message' => 'Award option removed.',
            'data' => $this->awardOptionsFromMetadata($event->fresh()),
        ]);
    }

    private function getSchoolEventOrFail(Request $request, int $eventId): CertificateEvent
    {
        return CertificateEvent::query()
            ->where('school_id', (int) $request->user()->school_id)
            ->findOrFail($eventId);
    }

    private function awardOptionsFromMetadata(CertificateEvent $event): array
    {
        $values = (array) data_get($event->metadata, 'award_options', []);

        return collect($values)
            ->map(fn ($item) => $this->normalizeAwardTitle((string) $item))
            ->filter(fn ($item) => $item !== '')
            ->reject(fn ($item) => $this->isAutoGeneratedAwardTitle((string) $item))
            ->unique(fn ($item) => strtolower($item))
            ->values()
            ->all();
    }

    private function saveAwardOptions(CertificateEvent $event, array $values): void
    {
        $normalized = collect($values)
            ->map(fn ($item) => $this->normalizeAwardTitle((string) $item))
            ->filter(fn ($item) => $item !== '')
            ->reject(fn ($item) => $this->isAutoGeneratedAwardTitle((string) $item))
            ->unique(fn ($item) => strtolower($item))
            ->values()
            ->all();

        $metadata = is_array($event->metadata) ? $event->metadata : [];
        $metadata['award_options'] = $normalized;

        $event->update([
            'metadata' => $metadata,
        ]);
    }

    private function normalizeAwardTitle(string $value): string
    {
        return trim(preg_replace('/\s+/', ' ', $value) ?? '');
    }

    private function isAutoGeneratedAwardTitle(string $value): bool
    {
        return in_array(strtolower($this->normalizeAwardTitle($value)), ['participant', 'participation', 'attendee', 'attendance'], true);
    }
}
