<?php

return [

    /*
    |--------------------------------------------------------------------------
    | THEME COLOR SYSTEM
    |--------------------------------------------------------------------------
    |
    | All possible Tailwind classes are declared statically here so JIT builds them.
    | Do NOT dynamically generate bg-*, text-*, etc. strings elsewhere.
    |
    | `hex` mirrors the `solid` shade and is what the header/sidebar actually
    | render as an inline background-color (build-independent). Keep the two in
    | sync — a missing `hex` silently falls back to slate #1e293b.
    |
    */

    'colors' => [

        'slate' => [
            'hex' => '#1e293b',
            'solid' => 'bg-slate-800',
            'gradient_vertical' => 'bg-gradient-to-b from-slate-700 to-slate-900',
            'gradient_horizontal' => 'bg-gradient-to-r from-slate-700 to-slate-900',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'black' => [
            'hex' => '#000000',
            'solid' => 'bg-black',
            'gradient_vertical' => 'bg-gradient-to-b from-neutral-800 to-black',
            'gradient_horizontal' => 'bg-gradient-to-r from-neutral-800 to-black',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'navy' => [
            'hex' => '#172554',
            'solid' => 'bg-blue-950',
            'gradient_vertical' => 'bg-gradient-to-b from-blue-900 to-blue-950',
            'gradient_horizontal' => 'bg-gradient-to-r from-blue-900 to-blue-950',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'blue' => [
            'hex' => '#1d4ed8',
            'solid' => 'bg-blue-700',
            'gradient_vertical' => 'bg-gradient-to-b from-blue-600 to-blue-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-blue-600 to-blue-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'purple' => [
            'hex' => '#7e22ce',
            'solid' => 'bg-purple-700',
            'gradient_vertical' => 'bg-gradient-to-b from-purple-600 to-purple-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-purple-600 to-purple-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'rose' => [
            'hex' => '#be123c',
            'solid' => 'bg-rose-700',
            'gradient_vertical' => 'bg-gradient-to-b from-rose-600 to-rose-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-rose-600 to-rose-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'amber' => [
            'hex' => '#d97706',
            'solid' => 'bg-amber-600',
            'gradient_vertical' => 'bg-gradient-to-b from-amber-500 to-amber-700',
            'gradient_horizontal' => 'bg-gradient-to-r from-amber-500 to-amber-700',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'emerald' => [
            'hex' => '#047857',
            'solid' => 'bg-emerald-700',
            'gradient_vertical' => 'bg-gradient-to-b from-emerald-600 to-emerald-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-emerald-600 to-emerald-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'cyan' => [
            'hex' => '#0e7490',
            'solid' => 'bg-cyan-700',
            'gradient_vertical' => 'bg-gradient-to-b from-cyan-600 to-cyan-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-cyan-600 to-cyan-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'indigo' => [
            'hex' => '#4338ca',
            'solid' => 'bg-indigo-700',
            'gradient_vertical' => 'bg-gradient-to-b from-indigo-600 to-indigo-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-indigo-600 to-indigo-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'teal' => [
            'hex' => '#0f766e',
            'solid' => 'bg-teal-700',
            'gradient_vertical' => 'bg-gradient-to-b from-teal-600 to-teal-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-teal-600 to-teal-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'fuchsia' => [
            'hex' => '#a21caf',
            'solid' => 'bg-fuchsia-700',
            'gradient_vertical' => 'bg-gradient-to-b from-fuchsia-600 to-fuchsia-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-fuchsia-600 to-fuchsia-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'white' => [
            'hex' => '#ffffff',
            'solid' => 'bg-white',
            'gradient_vertical' => 'bg-gradient-to-b from-gray-50 to-gray-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-gray-50 to-gray-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-gray-200',
            'border_light_mode' => 'border-gray-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'light' => [
            'hex' => '#f8fafc',
            'solid' => 'bg-slate-50',
            'gradient_vertical' => 'bg-gradient-to-b from-slate-50 to-slate-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-slate-50 to-slate-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-slate-200',
            'border_light_mode' => 'border-slate-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'silver' => [
            'hex' => '#f3f4f6',
            'solid' => 'bg-gray-100',
            'gradient_vertical' => 'bg-gradient-to-b from-gray-100 to-gray-200',
            'gradient_horizontal' => 'bg-gradient-to-r from-gray-100 to-gray-200',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-gray-300',
            'border_light_mode' => 'border-gray-300',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'sky' => [
            'hex' => '#f0f9ff',
            'solid' => 'bg-sky-50',
            'gradient_vertical' => 'bg-gradient-to-b from-sky-50 to-sky-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-sky-50 to-sky-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-slate-200',
            'border_light_mode' => 'border-slate-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
    ],
];
