<?php

return [

    /*
    |--------------------------------------------------------------------------
    | THEME COLOR SYSTEM
    |--------------------------------------------------------------------------
    |
    | All possible Tailwind classes are declared statically here so JIT builds them.
    | Do NOT dynamically generate bg-*, text-*, etc. strings elsewhere.
    |
    */

    'colors' => [

        'slate' => [
            'solid' => 'bg-slate-800',
            'gradient_vertical' => 'bg-gradient-to-b from-slate-700 to-slate-900',
            'gradient_horizontal' => 'bg-gradient-to-r from-slate-700 to-slate-900',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'blue' => [
            'solid' => 'bg-blue-700',
            'gradient_vertical' => 'bg-gradient-to-b from-blue-600 to-blue-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-blue-600 to-blue-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'purple' => [
            'solid' => 'bg-purple-700',
            'gradient_vertical' => 'bg-gradient-to-b from-purple-600 to-purple-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-purple-600 to-purple-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'rose' => [
            'solid' => 'bg-rose-700',
            'gradient_vertical' => 'bg-gradient-to-b from-rose-600 to-rose-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-rose-600 to-rose-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'amber' => [
            'solid' => 'bg-amber-600',
            'gradient_vertical' => 'bg-gradient-to-b from-amber-500 to-amber-700',
            'gradient_horizontal' => 'bg-gradient-to-r from-amber-500 to-amber-700',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'emerald' => [
            'solid' => 'bg-emerald-700',
            'gradient_vertical' => 'bg-gradient-to-b from-emerald-600 to-emerald-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-emerald-600 to-emerald-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'cyan' => [
            'solid' => 'bg-cyan-700',
            'gradient_vertical' => 'bg-gradient-to-b from-cyan-600 to-cyan-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-cyan-600 to-cyan-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'indigo' => [
            'solid' => 'bg-indigo-700',
            'gradient_vertical' => 'bg-gradient-to-b from-indigo-600 to-indigo-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-indigo-600 to-indigo-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'teal' => [
            'solid' => 'bg-teal-700',
            'gradient_vertical' => 'bg-gradient-to-b from-teal-600 to-teal-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-teal-600 to-teal-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'fuchsia' => [
            'solid' => 'bg-fuchsia-700',
            'gradient_vertical' => 'bg-gradient-to-b from-fuchsia-600 to-fuchsia-800',
            'gradient_horizontal' => 'bg-gradient-to-r from-fuchsia-600 to-fuchsia-800',
            'text_dark_mode' => 'text-white',
            'text_light_mode' => 'text-gray-900',
            'border_dark_mode' => 'border-white/10',
            'border_light_mode' => 'border-black/10',
            'hover_dark_mode' => 'hover:bg-white/10',
            'hover_light_mode' => 'hover:bg-black/10',
        ],
        'white' => [
            'solid' => 'bg-white',
            'gradient_vertical' => 'bg-gradient-to-b from-gray-50 to-gray-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-gray-50 to-gray-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-gray-200',
            'border_light_mode' => 'border-gray-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'light' => [
            'solid' => 'bg-slate-50',
            'gradient_vertical' => 'bg-gradient-to-b from-slate-50 to-slate-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-slate-50 to-slate-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-slate-200',
            'border_light_mode' => 'border-slate-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'silver' => [
            'solid' => 'bg-gray-100',
            'gradient_vertical' => 'bg-gradient-to-b from-gray-100 to-gray-200',
            'gradient_horizontal' => 'bg-gradient-to-r from-gray-100 to-gray-200',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-gray-300',
            'border_light_mode' => 'border-gray-300',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
        'sky' => [
            'solid' => 'bg-sky-50',
            'gradient_vertical' => 'bg-gradient-to-b from-sky-50 to-sky-100',
            'gradient_horizontal' => 'bg-gradient-to-r from-sky-50 to-sky-100',
            'text_dark_mode' => 'text-slate-900',
            'text_light_mode' => 'text-slate-900',
            'border_dark_mode' => 'border-slate-200',
            'border_light_mode' => 'border-slate-200',
            'hover_dark_mode' => 'hover:bg-black/5',
            'hover_light_mode' => 'hover:bg-black/5',
        ],
    ],
];